### ISSUE TITLE
mod 2 tester comments

### ISSUE THREAD

**Issue by kcudding** [quantitative-biology/module-2-rmarkdown#2]
## mod 2
- [x] too short. discussed: true, but code hadn't rendered properly on website, now corrected
- [x] more info on table formatting
- [x] and figure formatting(?) discussed: might be a separate section on formatting for pubs?
- [x] more info on calculating variables from data(?)
- [x] customizing text
- [x] bit disjointed and inconsistent (data generated in example was not used to create the figure). discussed: this comment related to missing code
- [X] how to see your Knit Directory (?) - not sure what this means
- [x] differences between knit to pdf, html
- [x]  resources are in one place at the end of the module.
- [x] Could still refer to LaTeX as an option for typsetting, but it seems to not mesh with the rest of the module that’s focused on RMarkdown; discussed: I think this text just needs to be a tiny bit clearer regarding how knitr works, and also maybe introduce equations here and the need for tinytex
- [x] Clarify: "Note that the .Rmd file is not repeating all the explanations that we gave above.”
- [x] instead of referring to Pandoc itself a more general discussion on open-source (R, Pandoc) might be a more clear summary for beginners
- [x] note how other languages are also supported by RMarkdown, for example Python, Julia, C++, and SQL
- [x] Word document, "It would also be useful to know how to specify font and size so you can readily paste it into your word doc." ---?  discussed: but this question is about figure formatting, not rmarkdown, and kind of misses the point about using RMarkdown.
- [x] make sure example saves as .Rmd not .txt
- [x] mention how to install packages
- [x] improved resolution of synopsis example figure? (hard as those files are huge, can try a .png)
- [x] see comment 17 onwards from student
- [x] why would the output from the exercise be .html rather than .pdf if this module is targeting biologists who would likely use RMarkdown for scientific documents. Because you need latex for .pdf, so this example is simplest.
- [x] need to mention .rmd available in rmarkdown module

RStudio related comments:
- [x] more info on the menu driven features in rstudio. discussed: maybe a new section
- [x] I would replace the discussion of LaTeX with more discussion on RMarkdown interface formatting - 'interface' implies RStudio I think
- [x] running chunks of code rather than whole thing (which is just like usual R code)
- [x] https://rmarkdown.rstudio.com/lesson-15.HTML - cheat sheet
- [x] video point & click on knitr. It's just clicking a button or typing a command, doesn't need a video.

ideas:
- [x] caching controls? I was going to mention this but the rmarkdown book says to try and avoid using caching (we use it a lot though), maybe a bit advanced
- [x] yaml
- [x] word rendering? - can mention but would not recommend it. Recommend sticking with one output format.
- [x] pdf rendering? - Can suggest changing the current example to .pdf by changing the yaml.
- [x] foreshadow... reassurance will try an example later  (??).

ideas for new sections
- [x] point and click stuff in R studio - see above
- [x] formatting for publication submission - could look for an example. Mention csasdown?

**Comment by andrew-edwards** [comment]
Done in further recent commits.
